const data = [
  {
    num: '1',
    name: 'Big ball with an image',
    count: '2',
    year: '1960',
    shape: 'ball',
    color: 'yellow',
    size: 'big',
    favorite: false,
  },
  {
    num: '2',
    name: 'Green ball with flowers',
    count: '5',
    year: '2000',
    shape: 'ball',
    color: 'green',
    size: 'big',
    favorite: false,
  },
  {
    num: '3',
    name: 'Matt red ball',
    count: '3',
    year: '1990',
    shape: 'ball',
    color: 'red',
    size: 'big',
    favorite: false,
  },
  {
    num: '4',
    name: 'Red icicle',
    count: '2',
    year: '1980',
    shape: 'toy',
    color: 'red',
    size: 'big',
    favorite: false,
  },
  {
    num: '5',
    name: 'Red grape',
    count: '4',
    year: '1980',
    shape: 'toy',
    color: 'red',
    size: 'medium',
    favorite: true,
  },
  {
    num: '6',
    name: 'Red ball with an image',
    count: '6',
    year: '2010',
    shape: 'ball',
    color: 'red',
    size: 'big',
    favorite: false,
  },
  {
    num: '7',
    name: 'Milky white ball',
    count: '12',
    year: '1960',
    shape: 'ball',
    color: 'white',
    size: 'medium',
    favorite: true,
  },
  {
    num: '8',
    name: 'Red ball',
    count: '10',
    year: '2010',
    shape: 'ball',
    color: 'red',
    size: 'big',
    favorite: false,
  },
  {
    num: '9',
    name: 'Ancient bell',
    count: '2',
    year: '1950',
    shape: 'bell',
    color: 'white',
    size: 'big',
    favorite: false,
  },
  {
    num: '10',
    name: 'White retro ball',
    count: '7',
    year: '1960',
    shape: 'ball',
    color: 'white',
    size: 'big',
    favorite: false,
  },
  {
    num: '11',
    name: 'White spruce cone',
    count: '11',
    year: '1960',
    shape: 'cone',
    color: 'white',
    size: 'small',
    favorite: false,
  },
  {
    num: '12',
    name: 'White ball with flowers',
    count: '5',
    year: '1980',
    shape: 'ball',
    color: 'white',
    size: 'big',
    favorite: false,
  },
  {
    num: '13',
    name: 'Painted ball River',
    count: '3',
    year: '1970',
    shape: 'ball',
    color: 'blue',
    size: 'big',
    favorite: true,
  },
  {
    num: '14',
    name: 'Painted ball Village',
    count: '4',
    year: '1970',
    shape: 'ball',
    color: 'blue',
    size: 'big',
    favorite: true,
  },
  {
    num: '15',
    name: 'Painted bell',
    count: '3',
    year: '1970',
    shape: 'bell',
    color: 'blue',
    size: 'medium',
    favorite: false,
  },
  {
    num: '16',
    name: 'Painted cone Landscape',
    count: '3',
    year: '1970',
    shape: 'cone',
    color: 'blue',
    size: 'medium',
    favorite: true,
  },
  {
    num: '17',
    name: 'Painted cone',
    count: '7',
    year: '1970',
    shape: 'cone',
    color: 'red',
    size: 'medium',
    favorite: false,
  },
  {
    num: '18',
    name: 'Yellow ball with ribbon',
    count: '2',
    year: '2010',
    shape: 'ball',
    color: 'yellow',
    size: 'big',
    favorite: false,
  },
  {
    num: '19',
    name: 'Yellow ball with sequins',
    count: '12',
    year: '1980',
    shape: 'ball',
    color: 'yellow',
    size: 'big',
    favorite: false,
  },
  {
    num: '20',
    name: 'Red ball with ribbon',
    count: '8',
    year: '1950',
    shape: 'ball',
    color: 'red',
    size: 'medium',
    favorite: true,
  },
  {
    num: '21',
    name: 'Red ball with stars',
    count: '4',
    year: '1970',
    shape: 'ball',
    color: 'red',
    size: 'big',
    favorite: true,
  },
  {
    num: '22',
    name: 'Gold spruce cone',
    count: '11',
    year: '1990',
    shape: 'cone',
    color: 'yellow',
    size: 'small',
    favorite: false,
  },
  {
    num: '23',
    name: 'Ancient bell',
    count: '9',
    year: '1950',
    shape: 'bell',
    color: 'yellow',
    size: 'big',
    favorite: false,
  },
  {
    num: '24',
    name: 'Graceful snowflake',
    count: '1',
    year: '1940',
    shape: 'snowflake',
    color: 'white',
    size: 'big',
    favorite: false,
  },
  {
    num: '25',
    name: 'Pink ball with sparkles',
    count: '12',
    year: '2010',
    shape: 'ball',
    color: 'red',
    size: 'big',
    favorite: false,
  },
  {
    num: '26',
    name: 'Ruby gold ball',
    count: '8',
    year: '1960',
    shape: 'ball',
    color: 'yellow',
    size: 'big',
    favorite: false,
  },
  {
    num: '27',
    name: 'Red ball with pattern',
    count: '4',
    year: '2010',
    shape: 'ball',
    color: 'red',
    size: 'big',
    favorite: false,
  },
  {
    num: '28',
    name: 'Burgundy ball with pattern',
    count: '10',
    year: '2010',
    shape: 'ball',
    color: 'red',
    size: 'big',
    favorite: false,
  },
  {
    num: '29',
    name: 'Ancient ball with flowers',
    count: '5',
    year: '1950',
    shape: 'ball',
    color: 'yellow',
    size: 'big',
    favorite: true,
  },
  {
    num: '30',
    name: 'Ancient ball with pattern',
    count: '8',
    year: '1950',
    shape: 'ball',
    color: 'yellow',
    size: 'big',
    favorite: true,
  },
  {
    num: '31',
    name: 'Red ball with sparkles',
    count: '8',
    year: '2010',
    shape: 'ball',
    color: 'red',
    size: 'big',
    favorite: false,
  },
  {
    num: '32',
    name: 'Blue ball Universe',
    count: '11',
    year: '1970',
    shape: 'ball',
    color: 'blue',
    size: 'big',
    favorite: false,
  },
  {
    num: '33',
    name: 'Blue ball with snowflake',
    count: '6',
    year: '2010',
    shape: 'ball',
    color: 'blue',
    size: 'medium',
    favorite: false,
  },
  {
    num: '34',
    name: 'Green  ball with pattern',
    count: '8',
    year: '2010',
    shape: 'ball',
    color: 'green',
    size: 'big',
    favorite: false,
  },
  {
    num: '35',
    name: 'Fox in a scarf toy',
    count: '8',
    year: '1950',
    shape: 'toy',
    color: 'yellow',
    size: 'medium',
    favorite: true,
  },
  {
    num: '36',
    name: 'Purple ball Snowstorm',
    count: '1',
    year: '2000',
    shape: 'ball',
    color: 'blue',
    size: 'big',
    favorite: false,
  },
  {
    num: '37',
    name: 'Green ball Snowstorm',
    count: '6',
    year: '2000',
    shape: 'ball',
    color: 'green',
    size: 'big',
    favorite: false,
  },
  {
    num: '38',
    name: 'Blue ball Snowstorm',
    count: '6',
    year: '2000',
    shape: 'ball',
    color: 'blue',
    size: 'big',
    favorite: false,
  },
  {
    num: '39',
    name: 'Red snowflake',
    count: '6',
    year: '1990',
    shape: 'snowflake',
    color: 'red',
    size: 'big',
    favorite: false,
  },
  {
    num: '40',
    name: 'Gold snowflake ',
    count: '12',
    year: '2020',
    shape: 'snowflake',
    color: 'yellow',
    size: 'big',
    favorite: false,
  },
  {
    num: '41',
    name: 'Arctic snowflake ',
    count: '11',
    year: '2020',
    shape: 'snowflake',
    color: 'white',
    size: 'big',
    favorite: false,
  },
  {
    num: '42',
    name: 'Green ball',
    count: '10',
    year: '1980',
    shape: 'ball',
    color: 'green',
    size: 'medium',
    favorite: false,
  },
  {
    num: '43',
    name: 'Bicolor snowflake ',
    count: '6',
    year: '1960',
    shape: 'snowflake',
    color: 'red',
    size: 'big',
    favorite: false,
  },
  {
    num: '44',
    name: 'Angel toy',
    count: '11',
    year: '1940',
    shape: 'toy',
    color: 'red',
    size: 'medium',
    favorite: true,
  },
  {
    num: '45',
    name: 'Christmas snowflake',
    count: '1',
    year: '1980',
    shape: 'snowflake',
    color: 'white',
    size: 'big',
    favorite: false,
  },
  {
    num: '46',
    name: 'Fly agaric toy',
    count: '10',
    year: '1950',
    shape: 'toy',
    color: 'red',
    size: 'small',
    favorite: false,
  },
  {
    num: '47',
    name: 'Well toy',
    count: '6',
    year: '1950',
    shape: 'toy',
    color: 'red',
    size: 'small',
    favorite: false,
  },
  {
    num: '48',
    name: 'Yellow ball with ribbon',
    count: '6',
    year: '1960',
    shape: 'ball',
    color: 'yellow',
    size: 'big',
    favorite: false,
  },
  {
    num: '49',
    name: 'Snowflake with turquoise',
    count: '4',
    year: '1980',
    shape: 'snowflake',
    color: 'yellow',
    size: 'big',
    favorite: false,
  },
  {
    num: '50',
    name: 'Bell big',
    count: '3',
    year: '2020',
    shape: 'bell',
    color: 'red',
    size: 'big',
    favorite: false,
  },
  {
    num: '51',
    name: 'Cone with rime',
    count: '12',
    year: '1970',
    shape: 'cone',
    color: 'red',
    size: 'small',
    favorite: false,
  },
  {
    num: '52',
    name: 'Red ball with an inscription',
    count: '12',
    year: '1990',
    shape: 'ball',
    color: 'red',
    size: 'big',
    favorite: true,
  },
  {
    num: '53',
    name: 'Silvery snowflake',
    count: '6',
    year: '2020',
    shape: 'snowflake',
    color: 'white',
    size: 'big',
    favorite: false,
  },
  {
    num: '54',
    name: 'Green ball with an image',
    count: '6',
    year: '2010',
    shape: 'ball',
    color: 'green',
    size: 'big',
    favorite: false,
  },
  {
    num: '55',
    name: 'Gingerbread house',
    count: '1',
    year: '1940',
    shape: 'toy',
    color: 'yellow',
    size: 'big',
    favorite: false,
  },
  {
    num: '56',
    name: 'Gingerbread teremok',
    count: '1',
    year: '1940',
    shape: 'toy',
    color: 'yellow',
    size: 'small',
    favorite: false,
  },
  {
    num: '57',
    name: 'Gingerbread hut',
    count: '1',
    year: '1940',
    shape: 'toy',
    color: 'yellow',
    size: 'medium',
    favorite: false,
  },
  {
    num: '58',
    name: 'White bear toy',
    count: '2',
    year: '1980',
    shape: 'toy',
    color: 'white',
    size: 'medium',
    favorite: false,
  },
  {
    num: '59',
    name: 'Yellow ball with an inscription',
    count: '10',
    year: '1990',
    shape: 'ball',
    color: 'yellow',
    size: 'medium',
    favorite: false,
  },
  {
    num: '60',
    name: 'Pigeon toy',
    count: '12',
    year: '1940',
    shape: 'toy',
    color: 'white',
    size: 'medium',
    favorite: true,
  },
];

export default data;
